image: golang:1.12

stages:
  - test
  - build

before_script:
  - go get -u github.com/golang/dep/cmd/dep
  - mkdir -p $GOPATH/src
  - cd $GOPATH/src
  - ln -s $CI_PROJECT_DIR
  - cd $CI_PROJECT_NAME
  - dep ensure

test:
  stage: test
  script:
    - go test

build:
  stage: build
  script:
    - go build
