# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
    - packr
builds:
  - env:
      - CGO_ENABLED=0
    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -s -w -X github.com/jimschubert/ossify/config.Version={{.Version}} -X github.com/jimschubert/ossify/config.Commit={{.ShortCommit}} -X github.com/jimschubert/ossify/config.Date={{.Date}} -X main.builtBy=goreleaser
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - 386
archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

    wrap_in_directory: '{{ .ProjectName }}-{{.Version}}'

    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^doc[s]?:'
      - '^\[doc[s]?\]'
      - '^wip:'
      - '^WIP:'
dockers:
  - goos: linux
    goarch: 386

    image_templates:
      - "jimschubert/{{ .ProjectName }}:latest"
      - "jimschubert/{{ .ProjectName }}:{{ .Tag }}"

    dockerfile: release.Dockerfile

    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--build-arg=APP_NAME={{ .ProjectName }}"